version: '3'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: jolvre
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "3305:3306"
  redis-server:
    image: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6378:6379"
    restart: always
  jolvre-server:
    image: jolvre-server
    build: .
    ports:
      - "8081:8080"

    env_file:
      - .env
    depends_on:
      - mysql-server
      - redis-server