version: '3'
volumes:
        jolvre_mysql:
                external: true
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    volumes:
      - jolvre_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: jolvre
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    env_file:
      - .env
    ports:
      - "3305:3306"
  redis-server:
    image: redis
    container_name: redis-server
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6378:6379"
    restart: always
  jolvre-server:
    image: jolvre-server
    container_name: jolvre-server
    build: .
    ports:
      - "8081:8080"

    env_file:
      - .env
    depends_on:
      - mysql-server
      - redis-server
